name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_secure_storage: ^9.2.2
  dio: ^5.4.3+1
  flutter_dotenv: ^5.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.3
  mask_text_input_formatter: ^2.4.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  http: ^1.2.2
  pdfx: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/pdfs/
    - assets/images/
