package ru.bowling.bowlingapp.DTO;

public enum NotificationEventType {
    MECHANIC_HELP_REQUESTED,
    MECHANIC_HELP_CONFIRMED,
    MECHANIC_HELP_DECLINED,
    MECHANIC_HELP_REASSIGNED,
    MAINTENANCE_WARNING,
    CLUB_ACCESS_REQUEST,
    SUPPLIER_COMPLAINT_UPDATE,
    FREE_MECHANIC_PENDING
}
